/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.0
 * Generated at: 2024-11-20 16:10:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


 /*if(session.getAttribute("name")==null)
 {
	 response.sendRedirect("login.jsp");
	 
 }*/



//Check if user is logged in and if their role is "Employee"
String role = (String) session.getAttribute("role");
if (session.getAttribute("name") == null || role == null || !"Employee".equals(role)) {
// Redirect to login page if user is not logged in or not an employee
response.sendRedirect("login.jsp");
return;
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Employee Landing</title>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.15.4/js/all.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/index-styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\t<!-- Navigation-->\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\"\r\n");
      out.write("\t\tid=\"mainNav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#page-top\">Role :");
      out.print(session.getAttribute("role") );
      out.write("</a>\r\n");
      out.write("\t\t\t<button\r\n");
      out.write("\t\t\t\tclass=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\"\r\n");
      out.write("\t\t\t\ttype=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\tMenu <i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"RequestServlet\">Softwares</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#portfolio\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"Logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1 bg-danger\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"Logout\">");
      out.print(session.getAttribute("name"));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Masthead-->\r\n");
      out.write("\t<header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("\t\t<div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("\t\t\t<!-- Masthead Avatar Image-->\r\n");
      out.write("\t\t\t<img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\"\r\n");
      out.write("\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t<!-- Masthead Heading-->\r\n");
      out.write("\t\t\t<h1 class=\"masthead-heading text-uppercase mb-0\">Welcome Employee Portal</h1>\r\n");
      out.write("\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t<div class=\"divider-custom divider-light\">\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Masthead Subheading-->\r\n");
      out.write("\t\t\t<p class=\"masthead-subheading font-weight-light mb-0\">");
      out.print(session.getAttribute("name"));
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- Portfolio Section-->\r\n");
      out.write("\t<section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Portfolio Section Heading-->\r\n");
      out.write("\t\t\t<h2\r\n");
      out.write("\t\t\t\tclass=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\r\n");
      out.write("\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Portfolio Grid Items-->\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 1-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal1\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/cabin.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 2-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal2\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/cake.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 3-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal3\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/circus.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 4-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal4\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/game.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 5-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal5\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/safe.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Portfolio Item 6-->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-bs-target=\"#portfolioModal6\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"portfolio-item-caption-content text-center text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid\" src=\"assets/img/portfolio/submarine.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"...\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- About Section-->\r\n");
      out.write("\t<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- About Section Heading-->\r\n");
      out.write("\t\t\t<h2\r\n");
      out.write("\t\t\t\tclass=\"page-section-heading text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t<div class=\"divider-custom divider-light\">\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- About Section Content-->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 ms-auto\">\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\"> we believe our people are our greatest asset.\r\n");
      out.write("\t\t\t\t\tThis space is designed to provide employees with seamless access to \r\n");
      out.write("\t\t\t\t\timportant resources, tools, and information that support both personal \r\n");
      out.write("\t\t\t\t\tand professional growth.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 me-auto\">\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\">Our mission is to foster a work environment that \r\n");
      out.write("\t\t\t\t\tencourages collaboration, innovation, and continuous learning. Here,\r\n");
      out.write("\t\t\t\t\tyou can explore company updates, manage your tasks, access training programs,\r\n");
      out.write("\t\t\t\t\tand stay connected with your team.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- About Section Button-->\r\n");
      out.write("\t\t\t<div class=\"text-center mt-4\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-xl btn-outline-light\"\r\n");
      out.write("\t\t\t\t\thref=\"https://startbootstrap.com/theme/freelancer/\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-download me-2\"></i> Free Download!\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Contact Section-->\r\n");
      out.write("\t<section class=\"page-section\" id=\"contact\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Contact Section Heading-->\r\n");
      out.write("\t\t\t<h2\r\n");
      out.write("\t\t\t\tclass=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Contact\r\n");
      out.write("\t\t\t\tMe</h2>\r\n");
      out.write("\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Contact Section Form-->\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("\t\t\t\t\t<!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("\t\t\t\t\t<!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("\t\t\t\t\t<!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("\t\t\t\t\t<!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("\t\t\t\t\t<!-- To make this form functional, sign up at-->\r\n");
      out.write("\t\t\t\t\t<!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("\t\t\t\t\t<!-- to get an API token!-->\r\n");
      out.write("\t\t\t\t\t<form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Name input-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control\" id=\"name\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter your name...\" data-sb-validations=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"name\">Full name</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A\r\n");
      out.write("\t\t\t\t\t\t\t\tname is required.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Email address input-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control\" id=\"email\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"name@example.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-sb-validations=\"required,email\" /> <label for=\"email\">Email\r\n");
      out.write("\t\t\t\t\t\t\t\taddress</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An\r\n");
      out.write("\t\t\t\t\t\t\t\temail is required.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email\r\n");
      out.write("\t\t\t\t\t\t\t\tis not valid.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Phone number input-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control\" id=\"phone\" type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"(123) 456-7890\" data-sb-validations=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"phone\">Phone number</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A\r\n");
      out.write("\t\t\t\t\t\t\t\tphone number is required.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Message input-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"message\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter your message here...\" style=\"height: 10rem\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-sb-validations=\"required\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"message\">Message</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A\r\n");
      out.write("\t\t\t\t\t\t\t\tmessage is required.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Submit success message-->\r\n");
      out.write("\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t<!-- This is what your users will see when the form-->\r\n");
      out.write("\t\t\t\t\t\t<!-- has successfully submitted-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("\t\t\t\t\t\t\t\tTo activate this form, sign up at <br /> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Submit error message-->\r\n");
      out.write("\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t\t\t<!-- This is what your users will see when there is-->\r\n");
      out.write("\t\t\t\t\t\t<!-- an error submitting the form-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-none\" id=\"submitErrorMessage\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center text-danger mb-3\">Error sending\r\n");
      out.write("\t\t\t\t\t\t\t\tmessage!</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Submit Button-->\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-xl disabled\" id=\"submitButton\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\">Send</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Footer-->\r\n");
      out.write("\t<footer class=\"footer text-center\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Footer Location-->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead mb-0\">\r\n");
      out.write("\t\t\t\t\t\t2215 Hi-Tech city Bhubaneswar <br /> Clark, MO 65243\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Footer Social Icons-->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-facebook-f\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-twitter\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-linkedin-in\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-dribbble\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Footer About Text-->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">About Theme</h4>\r\n");
      out.write("\t\t\t\t\t\tFreelance is a free to use, MIT licensed Bootstrap theme \r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://startbootstrap.com\">Start Bootstrap</a> .\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- Copyright Section-->\r\n");
      out.write("\t<div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<small>Copyright &copy; BHARAT: UserAccessManagement 2024</small>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modals-->\r\n");
      out.write("\t<!-- Portfolio Modal 1-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal1\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Log\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCabin</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/cabin.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modal 2-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal2\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Tasty\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCake</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/cake.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modal 3-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal3\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Circus\r\n");
      out.write("\t\t\t\t\t\t\t\t\tTent</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/circus.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modal 4-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal4\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Controller</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/game.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modal 5-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal5\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Locked\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSafe</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/safe.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Portfolio Modal 6-->\r\n");
      out.write("\t<div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\"\r\n");
      out.write("\t\ttabindex=\"-1\" aria-labelledby=\"portfolioModal6\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header border-0\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body text-center pb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Title-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Submarine</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Icon Divider-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-star\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"divider-custom-line\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid rounded mb-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"assets/img/portfolio/submarine.png\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio Modal - Text-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Mollitia neque assumenda ipsam nihil,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmolestias magnam, recusandae quos quis inventore quisquam velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tasperiores, vitae? Reprehenderit soluta, eos quod consequuntur\r\n");
      out.write("\t\t\t\t\t\t\t\t\titaque. Nam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" href=\"#!\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-times fa-fw\"></i> Close Window\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Bootstrap core JS-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<!-- Core theme JS-->\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("\t<!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("\t<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("\t<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("\t<script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
